name: any_image
description: "A universal Flutter image widget that renders any source"
version: 0.0.1
homepage: https://github.com/Sameer330/any_image

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  
